[package]
name = "xt"
version = "0.3.0"
authors = ["Joshua Toyota <jearsh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4.3"
csv = "1.1"
encoding = "0.2"
tui = "0.18"
crossterm = "0.23"
