[package]
name = "xl"
version = "0.1.0"
authors = ["Joshua Toyota <jearsh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
